# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DarkscapeTransferWindow(object):
    def setupUi(self, DarkscapeTransferWindow):
        DarkscapeTransferWindow.setObjectName("DarkscapeTransferWindow")
        DarkscapeTransferWindow.resize(535, 450)
        self.centralwidget = QtWidgets.QWidget(DarkscapeTransferWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 405))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.attack = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.attack.setText("")
        self.attack.setPixmap(QtGui.QPixmap("icons/attack.png"))
        self.attack.setObjectName("attack")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.attack)
        self.attack_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attack_level.sizePolicy().hasHeightForWidth())
        self.attack_level.setSizePolicy(sizePolicy)
        self.attack_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.attack_level.setFrame(True)
        self.attack_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.attack_level.setDragEnabled(False)
        self.attack_level.setObjectName("attack_level")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.attack_level)
        self.strength = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.strength.setText("")
        self.strength.setPixmap(QtGui.QPixmap("icons/strength.png"))
        self.strength.setObjectName("strength")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.strength)
        self.strength_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strength_level.sizePolicy().hasHeightForWidth())
        self.strength_level.setSizePolicy(sizePolicy)
        self.strength_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.strength_level.setFrame(True)
        self.strength_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strength_level.setDragEnabled(False)
        self.strength_level.setObjectName("strength_level")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.strength_level)
        self.defence = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.defence.setText("")
        self.defence.setPixmap(QtGui.QPixmap("icons/defence.png"))
        self.defence.setObjectName("defence")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.defence)
        self.defence_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defence_level.sizePolicy().hasHeightForWidth())
        self.defence_level.setSizePolicy(sizePolicy)
        self.defence_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.defence_level.setFrame(True)
        self.defence_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.defence_level.setDragEnabled(False)
        self.defence_level.setObjectName("defence_level")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.defence_level)
        self.range = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.range.setText("")
        self.range.setPixmap(QtGui.QPixmap("icons/range.png"))
        self.range.setObjectName("range")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.range)
        self.range_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.range_level.sizePolicy().hasHeightForWidth())
        self.range_level.setSizePolicy(sizePolicy)
        self.range_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.range_level.setFrame(True)
        self.range_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.range_level.setDragEnabled(False)
        self.range_level.setObjectName("range_level")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.range_level)
        self.prayer = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.prayer.setText("")
        self.prayer.setPixmap(QtGui.QPixmap("icons/prayer.png"))
        self.prayer.setObjectName("prayer")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.prayer)
        self.prayer_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prayer_level.sizePolicy().hasHeightForWidth())
        self.prayer_level.setSizePolicy(sizePolicy)
        self.prayer_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prayer_level.setFrame(True)
        self.prayer_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.prayer_level.setDragEnabled(False)
        self.prayer_level.setObjectName("prayer_level")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.prayer_level)
        self.magic = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.magic.setText("")
        self.magic.setPixmap(QtGui.QPixmap("icons/magic.png"))
        self.magic.setObjectName("magic")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.magic)
        self.magic_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magic_level.sizePolicy().hasHeightForWidth())
        self.magic_level.setSizePolicy(sizePolicy)
        self.magic_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.magic_level.setFrame(True)
        self.magic_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.magic_level.setDragEnabled(False)
        self.magic_level.setObjectName("magic_level")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.magic_level)
        self.runecrafting = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.runecrafting.setText("")
        self.runecrafting.setPixmap(QtGui.QPixmap("icons/runecrafting.png"))
        self.runecrafting.setObjectName("runecrafting")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.runecrafting)
        self.runecrafting_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runecrafting_level.sizePolicy().hasHeightForWidth())
        self.runecrafting_level.setSizePolicy(sizePolicy)
        self.runecrafting_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runecrafting_level.setFrame(True)
        self.runecrafting_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.runecrafting_level.setDragEnabled(False)
        self.runecrafting_level.setObjectName("runecrafting_level")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.runecrafting_level)
        self.construciton = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.construciton.setText("")
        self.construciton.setPixmap(QtGui.QPixmap("icons/construction.png"))
        self.construciton.setObjectName("construciton")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.construciton)
        self.construction_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.construction_level.sizePolicy().hasHeightForWidth())
        self.construction_level.setSizePolicy(sizePolicy)
        self.construction_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.construction_level.setFrame(True)
        self.construction_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.construction_level.setDragEnabled(False)
        self.construction_level.setObjectName("construction_level")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.construction_level)
        self.dungeoneering = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dungeoneering.setText("")
        self.dungeoneering.setPixmap(QtGui.QPixmap("icons/dungeoneering.png"))
        self.dungeoneering.setObjectName("dungeoneering")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.dungeoneering)
        self.dungeoneering_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dungeoneering_level.sizePolicy().hasHeightForWidth())
        self.dungeoneering_level.setSizePolicy(sizePolicy)
        self.dungeoneering_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dungeoneering_level.setFrame(True)
        self.dungeoneering_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dungeoneering_level.setDragEnabled(False)
        self.dungeoneering_level.setObjectName("dungeoneering_level")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dungeoneering_level)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.constitution = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.constitution.setText("")
        self.constitution.setPixmap(QtGui.QPixmap("icons/constitution.png"))
        self.constitution.setObjectName("constitution")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.constitution)
        self.agility = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.agility.setText("")
        self.agility.setPixmap(QtGui.QPixmap("icons/agility.png"))
        self.agility.setObjectName("agility")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.agility)
        self.herblore = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.herblore.setText("")
        self.herblore.setPixmap(QtGui.QPixmap("icons/herblore.png"))
        self.herblore.setObjectName("herblore")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.herblore)
        self.thieving = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.thieving.setText("")
        self.thieving.setPixmap(QtGui.QPixmap("icons/thieving.png"))
        self.thieving.setObjectName("thieving")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.thieving)
        self.crafting = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.crafting.setText("")
        self.crafting.setPixmap(QtGui.QPixmap("icons/crafting.png"))
        self.crafting.setObjectName("crafting")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.crafting)
        self.fletchhing = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fletchhing.setText("")
        self.fletchhing.setPixmap(QtGui.QPixmap("icons/fletching.png"))
        self.fletchhing.setObjectName("fletchhing")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.fletchhing)
        self.slayer = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.slayer.setText("")
        self.slayer.setPixmap(QtGui.QPixmap("icons/slayer.png"))
        self.slayer.setObjectName("slayer")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.slayer)
        self.hunter = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hunter.setText("")
        self.hunter.setPixmap(QtGui.QPixmap("icons/hunter.png"))
        self.hunter.setObjectName("hunter")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.hunter)
        self.divination = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.divination.setText("")
        self.divination.setPixmap(QtGui.QPixmap("icons/divination.png"))
        self.divination.setObjectName("divination")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.divination)
        self.constitution_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constitution_level.sizePolicy().hasHeightForWidth())
        self.constitution_level.setSizePolicy(sizePolicy)
        self.constitution_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.constitution_level.setFrame(True)
        self.constitution_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.constitution_level.setDragEnabled(False)
        self.constitution_level.setObjectName("constitution_level")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.constitution_level)
        self.agility_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agility_level.sizePolicy().hasHeightForWidth())
        self.agility_level.setSizePolicy(sizePolicy)
        self.agility_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.agility_level.setFrame(True)
        self.agility_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.agility_level.setDragEnabled(False)
        self.agility_level.setObjectName("agility_level")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.agility_level)
        self.herblore_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.herblore_level.sizePolicy().hasHeightForWidth())
        self.herblore_level.setSizePolicy(sizePolicy)
        self.herblore_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.herblore_level.setFrame(True)
        self.herblore_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.herblore_level.setDragEnabled(False)
        self.herblore_level.setObjectName("herblore_level")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.herblore_level)
        self.thieving_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thieving_level.sizePolicy().hasHeightForWidth())
        self.thieving_level.setSizePolicy(sizePolicy)
        self.thieving_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thieving_level.setFrame(True)
        self.thieving_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.thieving_level.setDragEnabled(False)
        self.thieving_level.setObjectName("thieving_level")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.thieving_level)
        self.crafting_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crafting_level.sizePolicy().hasHeightForWidth())
        self.crafting_level.setSizePolicy(sizePolicy)
        self.crafting_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.crafting_level.setFrame(True)
        self.crafting_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.crafting_level.setDragEnabled(False)
        self.crafting_level.setObjectName("crafting_level")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.crafting_level)
        self.fletching_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fletching_level.sizePolicy().hasHeightForWidth())
        self.fletching_level.setSizePolicy(sizePolicy)
        self.fletching_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fletching_level.setFrame(True)
        self.fletching_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fletching_level.setDragEnabled(False)
        self.fletching_level.setObjectName("fletching_level")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fletching_level)
        self.slayer_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slayer_level.sizePolicy().hasHeightForWidth())
        self.slayer_level.setSizePolicy(sizePolicy)
        self.slayer_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slayer_level.setFrame(True)
        self.slayer_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slayer_level.setDragEnabled(False)
        self.slayer_level.setObjectName("slayer_level")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.slayer_level)
        self.hunter_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hunter_level.sizePolicy().hasHeightForWidth())
        self.hunter_level.setSizePolicy(sizePolicy)
        self.hunter_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hunter_level.setFrame(True)
        self.hunter_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hunter_level.setDragEnabled(False)
        self.hunter_level.setObjectName("hunter_level")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.hunter_level)
        self.divination_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.divination_level.sizePolicy().hasHeightForWidth())
        self.divination_level.setSizePolicy(sizePolicy)
        self.divination_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.divination_level.setFrame(True)
        self.divination_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.divination_level.setDragEnabled(False)
        self.divination_level.setObjectName("divination_level")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.divination_level)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.mining = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mining.setText("")
        self.mining.setPixmap(QtGui.QPixmap("icons/mining.png"))
        self.mining.setObjectName("mining")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mining)
        self.smithing = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.smithing.setText("")
        self.smithing.setPixmap(QtGui.QPixmap("icons/smithing.png"))
        self.smithing.setObjectName("smithing")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.smithing)
        self.fishing = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fishing.setText("")
        self.fishing.setPixmap(QtGui.QPixmap("icons/fishing.png"))
        self.fishing.setObjectName("fishing")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fishing)
        self.cooking = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cooking.setText("")
        self.cooking.setPixmap(QtGui.QPixmap("icons/cooking.png"))
        self.cooking.setObjectName("cooking")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cooking)
        self.firemaking = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.firemaking.setText("")
        self.firemaking.setPixmap(QtGui.QPixmap("icons/firemaking.png"))
        self.firemaking.setObjectName("firemaking")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.firemaking)
        self.woodcutting = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.woodcutting.setText("")
        self.woodcutting.setPixmap(QtGui.QPixmap("icons/woodcutting.png"))
        self.woodcutting.setObjectName("woodcutting")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.woodcutting)
        self.farming = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.farming.setText("")
        self.farming.setPixmap(QtGui.QPixmap("icons/farming.png"))
        self.farming.setObjectName("farming")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.farming)
        self.summoning = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.summoning.setText("")
        self.summoning.setPixmap(QtGui.QPixmap("icons/summoning.png"))
        self.summoning.setObjectName("summoning")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.summoning)
        self.mining_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mining_level.sizePolicy().hasHeightForWidth())
        self.mining_level.setSizePolicy(sizePolicy)
        self.mining_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mining_level.setFrame(True)
        self.mining_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mining_level.setDragEnabled(False)
        self.mining_level.setObjectName("mining_level")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mining_level)
        self.smithing_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smithing_level.sizePolicy().hasHeightForWidth())
        self.smithing_level.setSizePolicy(sizePolicy)
        self.smithing_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.smithing_level.setFrame(True)
        self.smithing_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.smithing_level.setDragEnabled(False)
        self.smithing_level.setObjectName("smithing_level")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.smithing_level)
        self.fishing_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fishing_level.sizePolicy().hasHeightForWidth())
        self.fishing_level.setSizePolicy(sizePolicy)
        self.fishing_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fishing_level.setFrame(True)
        self.fishing_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fishing_level.setDragEnabled(False)
        self.fishing_level.setObjectName("fishing_level")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fishing_level)
        self.cooking_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cooking_level.sizePolicy().hasHeightForWidth())
        self.cooking_level.setSizePolicy(sizePolicy)
        self.cooking_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cooking_level.setFrame(True)
        self.cooking_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cooking_level.setDragEnabled(False)
        self.cooking_level.setObjectName("cooking_level")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cooking_level)
        self.firemaking_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firemaking_level.sizePolicy().hasHeightForWidth())
        self.firemaking_level.setSizePolicy(sizePolicy)
        self.firemaking_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.firemaking_level.setFrame(True)
        self.firemaking_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.firemaking_level.setDragEnabled(False)
        self.firemaking_level.setObjectName("firemaking_level")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.firemaking_level)
        self.woodcutting_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.woodcutting_level.sizePolicy().hasHeightForWidth())
        self.woodcutting_level.setSizePolicy(sizePolicy)
        self.woodcutting_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.woodcutting_level.setFrame(True)
        self.woodcutting_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.woodcutting_level.setDragEnabled(False)
        self.woodcutting_level.setObjectName("woodcutting_level")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.woodcutting_level)
        self.farming_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.farming_level.sizePolicy().hasHeightForWidth())
        self.farming_level.setSizePolicy(sizePolicy)
        self.farming_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.farming_level.setFrame(True)
        self.farming_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.farming_level.setDragEnabled(False)
        self.farming_level.setObjectName("farming_level")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.farming_level)
        self.summoning_level = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summoning_level.sizePolicy().hasHeightForWidth())
        self.summoning_level.setSizePolicy(sizePolicy)
        self.summoning_level.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.summoning_level.setFrame(True)
        self.summoning_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.summoning_level.setDragEnabled(False)
        self.summoning_level.setObjectName("summoning_level")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.summoning_level)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.rs3_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.rs3_name.setObjectName("rs3_name")
        self.verticalLayout_2.addWidget(self.rs3_name)
        self.get_stats_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.get_stats_button.setObjectName("get_stats_button")
        self.verticalLayout_2.addWidget(self.get_stats_button)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        DarkscapeTransferWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DarkscapeTransferWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DarkscapeTransferWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DarkscapeTransferWindow)
        self.statusbar.setObjectName("statusbar")
        DarkscapeTransferWindow.setStatusBar(self.statusbar)
        self.action_about = QtWidgets.QAction(DarkscapeTransferWindow)
        self.action_about.setObjectName("action_about")
        self.action_exit = QtWidgets.QAction(DarkscapeTransferWindow)
        self.action_exit.setObjectName("action_exit")
        self.menuFile.addAction(self.action_about)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(DarkscapeTransferWindow)
        QtCore.QMetaObject.connectSlotsByName(DarkscapeTransferWindow)

    def retranslateUi(self, DarkscapeTransferWindow):
        _translate = QtCore.QCoreApplication.translate
        DarkscapeTransferWindow.setWindowTitle(_translate("DarkscapeTransferWindow", "Darkscape EXP Transfer"))
        self.attack_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.attack_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.strength_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.strength_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.defence_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.defence_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.range_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.range_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.prayer_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.prayer_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.magic_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.magic_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.runecrafting_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.runecrafting_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.construction_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.construction_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.dungeoneering_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.dungeoneering_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.constitution_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.constitution_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.agility_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.agility_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.herblore_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.herblore_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.thieving_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.thieving_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.crafting_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.crafting_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.fletching_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.fletching_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.slayer_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.slayer_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.hunter_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.hunter_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.divination_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.divination_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.mining_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.mining_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.smithing_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.smithing_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.fishing_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.fishing_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.cooking_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.cooking_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.firemaking_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.firemaking_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.woodcutting_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.woodcutting_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.farming_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.farming_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.summoning_level.setText(_translate("DarkscapeTransferWindow", "1"))
        self.summoning_level.setPlaceholderText(_translate("DarkscapeTransferWindow", "level"))
        self.rs3_name.setPlaceholderText(_translate("DarkscapeTransferWindow", "RS3 Name"))
        self.get_stats_button.setText(_translate("DarkscapeTransferWindow", "Get RS3 Stats After Transfer"))
        self.menuFile.setTitle(_translate("DarkscapeTransferWindow", "File"))
        self.action_about.setText(_translate("DarkscapeTransferWindow", "About"))
        self.action_exit.setText(_translate("DarkscapeTransferWindow", "Exit"))
        self.action_exit.setShortcut(_translate("DarkscapeTransferWindow", "Ctrl+Q"))

